# Generated by Django 5.1.6 on 2025-02-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_transactionreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='name_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name_walet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.walet'),
        ),
    ]
