# Generated by Django 5.1.6 on 2025-02-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_alter_transactionreceipt_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
            ],
        ),
    ]
